---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[chef-3scale::default]
    attributes:
      3scale:
        provider-key: <%= ENV['THREESCALE_PROVIDER_KEY'] %>
        admin-domain: <%= ENV['THREESCALE_ADMIN_DOMAIN'] %>
        config-source: 'local'
      openresty:
        source:
          prefix: "/etc"
