---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[chef-3scale::default]
    attributes:
      openresty:
        source:
          prefix: "/etc"